print("Welcome to the Interactive Personmal date Collector!")
print()
Name=str(input("Please enter your name:"))
age=int(input("Please enter your age:"))
Height=float(input("Please enter your height in meters:"))
favnumber=int(input("Please enetr your favourite number:"))
print()
print("Thank you! Here is the information we collected:")

print("Name:",Name,"(",type(Name),"Memory Address:",id(Name),Name,")")
print("age:",age,"(",type(age),"Memory Address:",id(age),age,")")
print("Height:",Height,"(",type(Height),"Memory Address:",id(Height),Height,")")
print("favnumber:",favnumber,"(",type(favnumber),"Memory Address:",id(favnumber),favnumber,")")
print()
print("your birth year is approxmately:",end="")
print(2025-19)
print()
print("Thank you for using the Presonal Data Collector.Goodbye!")